import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { app } from '../firebase/firebase-config';

const Home: NextPage = () => {

  console.log(app);
  
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full text-center font-bold text-6xl'>
        Hello World

      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
